---
abstract: 'Fix as much of Perl 5 as possible in one pragma'
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  ExtUtils::CBuilder: '0.26'
  IPC::Open3: '0'
  Test::More: '0.88'
  Test::Output: '0.16'
  Test::Warn: '0.11'
configure_requires:
  Module::Build: '0.36'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: perl5i
no_index:
  file:
    - lib/perl5i/0/DateTime.pm
    - lib/perl5i/0/ARRAY.pm
    - lib/perl5i/0/DEFAULT.pm
    - lib/perl5i/0/HASH.pm
    - lib/perl5i/0/Meta.pm
    - lib/perl5i/0/Meta/Class.pm
    - lib/perl5i/0/Meta/Instance.pm
    - lib/perl5i/0/SCALAR.pm
    - lib/perl5i/VERSION.pm
provides:
  perl5i:
    file: lib/perl5i.pm
    version: v2.13.0
  perl5i::0:
    file: lib/perl5i/0.pm
    version: v2.13.0
  perl5i::0::ARRAY:
    file: lib/perl5i/0/ARRAY.pm
  perl5i::0::DEFAULT:
    file: lib/perl5i/0/DEFAULT.pm
  perl5i::0::DateTime:
    file: lib/perl5i/0/DateTime.pm
  perl5i::0::DateTime::Format::CTime:
    file: lib/perl5i/0/DateTime.pm
  perl5i::0::DateTime::time:
    file: lib/perl5i/0/DateTime.pm
  perl5i::0::DateTime::y2038:
    file: lib/perl5i/0/DateTime.pm
  perl5i::0::HASH:
    file: lib/perl5i/0/HASH.pm
  perl5i::0::Meta:
    file: lib/perl5i/0/Meta.pm
  perl5i::0::Meta::Class:
    file: lib/perl5i/0/Meta/Class.pm
  perl5i::0::Meta::Instance:
    file: lib/perl5i/0/Meta/Instance.pm
  perl5i::0::SCALAR:
    file: lib/perl5i/0/SCALAR.pm
  perl5i::1:
    file: lib/perl5i/1.pm
    version: v2.13.0
  perl5i::1::ARRAY:
    file: lib/perl5i/1/ARRAY.pm
  perl5i::1::CODE:
    file: lib/perl5i/1/CODE.pm
  perl5i::1::DateTime:
    file: lib/perl5i/1/DateTime.pm
  perl5i::1::DateTime::Format::CTime:
    file: lib/perl5i/1/DateTime.pm
  perl5i::1::DateTime::time:
    file: lib/perl5i/1/DateTime.pm
  perl5i::1::DateTime::y2038:
    file: lib/perl5i/1/DateTime.pm
  perl5i::1::HASH:
    file: lib/perl5i/1/HASH.pm
  perl5i::1::Meta:
    file: lib/perl5i/1/Meta.pm
  perl5i::1::Meta::Class:
    file: lib/perl5i/1/Meta/Class.pm
  perl5i::1::Meta::Instance:
    file: lib/perl5i/1/Meta/Instance.pm
  perl5i::1::SCALAR:
    file: lib/perl5i/1/SCALAR.pm
  perl5i::1::UNIVERSAL:
    file: lib/perl5i/1/UNIVERSAL.pm
  perl5i::1::autobox:
    file: lib/perl5i/1/autobox.pm
  perl5i::2:
    file: lib/perl5i/2.pm
    version: v2.13.0
  perl5i::2::ARRAY:
    file: lib/perl5i/2/ARRAY.pm
  perl5i::2::CODE:
    file: lib/perl5i/2/CODE.pm
  perl5i::2::DateTime:
    file: lib/perl5i/2/DateTime.pm
  perl5i::2::DateTime::Format::CTime:
    file: lib/perl5i/2/DateTime.pm
  perl5i::2::DateTime::time:
    file: lib/perl5i/2/DateTime.pm
  perl5i::2::DateTime::y2038:
    file: lib/perl5i/2/DateTime.pm
  perl5i::2::HASH:
    file: lib/perl5i/2/HASH.pm
  perl5i::2::Meta:
    file: lib/perl5i/2/Meta.pm
  perl5i::2::Meta::Class:
    file: lib/perl5i/2/Meta/Class.pm
  perl5i::2::Meta::Instance:
    file: lib/perl5i/2/Meta/Instance.pm
  perl5i::2::RequireMessage:
    file: lib/perl5i/2/RequireMessage.pm
  perl5i::2::SCALAR:
    file: lib/perl5i/2/SCALAR.pm
  perl5i::2::Signature:
    file: lib/perl5i/2/Signature.pm
  perl5i::2::Signature::Function::None:
    file: lib/perl5i/2/Signature/Function/None.pm
  perl5i::2::Signature::Method::None:
    file: lib/perl5i/2/Signature/Method/None.pm
  perl5i::2::Signature::None:
    file: lib/perl5i/2/Signature/None.pm
  perl5i::2::Signature::Real:
    file: lib/perl5i/2/Signature/Real.pm
  perl5i::2::Signatures:
    file: lib/perl5i/2/Signatures.pm
  perl5i::2::UNIVERSAL:
    file: lib/perl5i/2/UNIVERSAL.pm
  perl5i::2::autobox:
    file: lib/perl5i/2/autobox.pm
  perl5i::2::equal:
    file: lib/perl5i/2/equal.pm
  perl5i::VERSION:
    file: lib/perl5i/VERSION.pm
    version: v2.13.0
  perl5i::cmd:
    file: lib/perl5i/cmd.pm
  perl5i::latest:
    file: lib/perl5i/latest.pm
    version: v2.13.0
requires:
  CLASS: '1.00'
  Capture::Tiny: '0.06'
  Carp::Fix::1_25: '1.000000'
  Child: '0.009'
  DateTime: '0.47'
  DateTime::Format::Epoch: '0.11'
  DateTime::TimeZone::Tzfile: '0.002'
  Devel::Declare::MethodInstaller::Simple: '0.006009'
  Digest::MD5: '2.36'
  Digest::SHA: '5.45'
  File::chdir: '0.1002'
  Hash::FieldHash: '0.06'
  Hash::Merge::Simple: '0.04'
  Hash::StoredIterator: '0.007'
  IPC::System::Simple: '1.18'
  JSON: '2.17'
  List::MoreUtils: '0.22'
  Modern::Perl: '1.03'
  Module::Load: '0.16'
  Object::ID: v0.1.0
  Path::Tiny: '0.036'
  Perl6::Caller: '0.100'
  Taint::Util: '0.06'
  Text::Wrap: '2009.0305'
  Try::Tiny: '0.02'
  Want: '0.18'
  YAML::Any: '0.70'
  autobox: '2.70'
  autobox::Core: '1.0'
  autobox::List::Util: '20090629'
  autobox::dump: '20090426'
  autodie: '2.12'
  autovivification: '0.06'
  indirect: '0.24'
  parent: '0.221'
  perl: v5.10.0
  true::VERSION: '0.16'
  utf8::all: '0.002'
  version: '0.77'
resources:
  Chat: irc://irc.perl.org/#perl5i
  bugtracker: http://github.com/evalEmpire/perl5i/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/evalEmpire/perl5i/tree/master
version: v2.13.0
